variable "vpc-name" {}
variable "vpc-cidr" {}
variable "igw-name" {}
variable "public-cidr1" {}
variable "public-subnet1" {}
variable "public-cidr2" {}
variable "public-subnet2" {}
variable "private-cidr1" {}
variable "private-subnet1" {}
variable "private-cidr2" {}
variable "private-subnet2" {}
variable "db-cidr1" {}
variable "db-subnet1" {}
variable "db-cidr2" {}
variable "db-subnet2" {}
variable "eip-name1" {}
variable "eip-name2" {}
variable "ngw-name1" {}
variable "ngw-name2" {}
variable "public-rt-name1" {}
variable "public-rt-name2" {}
variable "private-rt-name1" {}
variable "private-rt-name2" {}
variable "db-rt-name1" {}
variable "db-rt-name2" {}